import { StyleSheet } from "react-native";
import { DesignSystem } from "../../theme/designSystem";

export const completionHistoryStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  heroContainer: {
    position: "relative",
    overflow: "hidden",
    paddingBottom: DesignSystem.spacing.lg,
    paddingHorizontal: DesignSystem.spacing.md,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.05,
    shadowRadius: 4,
    elevation: 2,
    paddingTop: DesignSystem.spacing.xl + DesignSystem.spacing.md,
  },
  bottomFade: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 150,
    zIndex: 10,
  },
  gradientBase: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
    opacity: 1,
  },
  gradientGlow: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  gradientAmbient: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 1,
  },
  contentLayer: {
    paddingTop: DesignSystem.spacing.xl + DesignSystem.spacing.md,
    paddingBottom: DesignSystem.spacing.lg,
    paddingHorizontal: DesignSystem.spacing.md,
    position: "relative",
    zIndex: 15,
  },
  backButton: {
    position: "absolute",
    top: DesignSystem.spacing.md,
    left: DesignSystem.spacing.md,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  heroContent: {
    alignItems: "center",
    paddingTop: DesignSystem.spacing.md,
    position: "relative",
    zIndex: 15,
  },
  heroTitle: {
    ...DesignSystem.typography.h1,
    fontSize: 32,
    textAlign: "center",
    marginBottom: DesignSystem.spacing.md,
    fontWeight: "800",
    letterSpacing: -0.5,
    textShadowColor: "rgba(0, 0, 0, 0.15)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  heroSubtitle: {
    ...DesignSystem.typography.body,
    textAlign: "center",
    marginTop: DesignSystem.spacing.xs,
    textShadowColor: "rgba(0, 0, 0, 0.1)",
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  routinesList: {
    padding: DesignSystem.spacing.md,
    gap: DesignSystem.spacing.md,
  },
  routineItem: {
    borderRadius: DesignSystem.borders.radius.medium,
    padding: DesignSystem.spacing.md,
    borderWidth: 1,
    ...DesignSystem.shadows.medium,
    marginBottom: DesignSystem.spacing.md,
  },
  routineHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: DesignSystem.spacing.lg,
  },
  routineHeaderLeft: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    gap: DesignSystem.spacing.sm,
  },
  routineHeaderRight: {
    alignItems: "center",
    justifyContent: "center",
  },
  routineTitle: {
    ...DesignSystem.typography.bodySemiBold,
    fontSize: 18,
    lineHeight: 24,
    flex: 1,
  },
  categoryBadge: {
    paddingHorizontal: DesignSystem.spacing.sm,
    paddingVertical: DesignSystem.spacing.xs,
    borderRadius: DesignSystem.borders.radius.small,
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
  },
  categoryText: {
    ...DesignSystem.typography.captionSemiBold,
    fontSize: 12,
    fontWeight: "600",
  },
  progressContainer: {
    marginBottom: DesignSystem.spacing.md,
  },
  progressBar: {
    marginBottom: DesignSystem.spacing.sm,
  },
  progressBarBackground: {
    height: 8,
    backgroundColor: "rgba(0,0,0,0.1)",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    borderRadius: 4,
  },
  progressStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  progressStat: {
    flexDirection: "row",
    alignItems: "center",
    gap: DesignSystem.spacing.xs,
  },
  progressText: {
    ...DesignSystem.typography.caption,
    fontSize: 12,
  },
  lastCompletion: {
    flexDirection: "row",
    alignItems: "center",
    gap: DesignSystem.spacing.sm,
    marginBottom: DesignSystem.spacing.md,
    paddingHorizontal: DesignSystem.spacing.sm,
  },
  lastCompletionText: {
    ...DesignSystem.typography.caption,
    fontSize: 12,
  },
  instanceDetails: {
    borderTopWidth: 1,
    borderTopColor: "rgba(0,0,0,0.08)",
    paddingTop: DesignSystem.spacing.md,
  },
  instanceTitle: {
    ...DesignSystem.typography.bodySemiBold,
    marginBottom: DesignSystem.spacing.sm,
    fontSize: 14,
  },
  instanceItem: {
    paddingVertical: DesignSystem.spacing.xs,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(0,0,0,0.04)",
  },
  completeButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: DesignSystem.spacing.sm,
    paddingHorizontal: DesignSystem.spacing.md,
    borderRadius: DesignSystem.borders.radius.small,
    marginTop: DesignSystem.spacing.sm,
    gap: DesignSystem.spacing.xs,
  },
  completeButtonText: {
    ...DesignSystem.typography.captionSemiBold,
    fontSize: 12,
    fontWeight: "600",
  },
  instanceHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  instanceDate: {
    ...DesignSystem.typography.caption,
    fontSize: 12,
  },
  instancePriority: {
    flexDirection: "row",
    alignItems: "center",
    gap: DesignSystem.spacing.xs,
  },
  priorityText: {
    ...DesignSystem.typography.caption,
    fontSize: 11,
    textTransform: "capitalize",
  },
  detailText: {
    ...DesignSystem.typography.body,
    fontSize: 14,
  },
  priorityIndicator: {
    width: 10,
    height: 10,
    borderRadius: 5,
    marginRight: DesignSystem.spacing.xs,
  },
  emptyState: {
    alignItems: "center",
    paddingVertical: DesignSystem.spacing.xxl,
  },
  emptyStateTitle: {
    ...DesignSystem.typography.h2,
    marginTop: DesignSystem.spacing.md,
    marginBottom: DesignSystem.spacing.sm,
  },
  emptyStateSubtitle: {
    ...DesignSystem.typography.body,
    textAlign: "center",
    opacity: 0.7,
  },
});
